### ISSUE TITLE
Failed to render and update auto layout status for ViewController 

### ISSUE THREAD

**Issue by thomasmbr** [AladinWay/TransitionButton#21] opened 2018-06-09 18:41 UTC
Hello guys,
Did either of you get this kind of error while using the TransitionButton? The project compiles normally, but this error persists when you open the storyboard.

![captura de tela 2018-06-09 as 15 37 33](https://user-images.githubusercontent.com/13890644/41194979-30d3f5f0-6bfb-11e8-9ce8-ad5f49cd986a.png)

**Comment by KheniDharmesh** [comment] 2018-06-13 12:43
Getting same error please help.I can not see views because of this error.

**Comment by s3734322** [comment] 2018-07-20 13:55
According to Stackoverflow there is a workaround with Cocoapods.

Maybe you should try this answer since you doesn't have an official reply on your issue.

https://stackoverflow.com/questions/49764064/failed-to-render-and-update-auto-layout-status-for-uiviewcontroller-dlopencos

**Comment by AladinWay** [comment] 2018-07-22 14:37
I'm trying to investigate the issue and fix it, but I can't reproduce the issue. Can anyone please provide an example project with the issue ? @thomasmbr @KheniDharmesh  @s3734322

**Comment by KheniDharmesh** [comment] 2018-07-23 06:08
Here is the demo project for that:

[DemoWithTransitionButton.zip](https://github.com/AladinWay/TransitionButton/files/2218074/DemoWithTransitionButton.zip)

If you open Main.Storyboard file I have added a button there which has a class `TransitionButton` and if you build a project you will get a same error.

Xcode version is 9.4.

**Comment by AladinWay** [comment] 2018-07-23 11:52
@KheniDharmesh  thank you for providing an example project. 
Actually, this issue is related to CocoaPods https://github.com/CocoaPods/CocoaPods/issues/7606 so it's up to them to fix the issue. You can follow the issue https://github.com/CocoaPods/CocoaPods/issues/7606 to see the workarounds until they provide a fix. I will close the issue for now since there is nothing that I can do. It's up to CocoaPods Team to fix it.

**Closed as completed by AladinWay** 2018-07-23 11:52 UTC

**Comment by dachev** [comment] 2019-08-13 21:52
None of the suggested workarounds on the CocoaPods repo worked for me. However, I was able to make the error go away by using `use_frameworks!`
